# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  path:
    required: true
    description: ''
    default: 'World'
runs:
  using: 'docker'
  image: "${{ inputs.path }}"

