on:
  # Trigger the workflow on push or pull request ${{ github.event.pull_request.title }}
  pull_request:
# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  path:
    required: true
    description: ''
    default: 'World'
runs:
  using: 'docker'
  image: ${{ inputs.path }}
